var vocab = [
	{
		category: "Numbers (Native Korean)",
		entries: [
			{ eng: "1", kor: "하나" },
			{ eng: "2", kor: "둘" },
			{ eng: "3", kor: "셋" },
			{ eng: "4", kor: "넷" },
			{ eng: "5", kor: "다섯" },
			{ eng: "6", kor: "여섯" },
			{ eng: "7", kor: "일곱" },
			{ eng: "8", kor: "여덟" },
			{ eng: "9", kor: "아홉" },
			{ eng: "10", kor: "열" },
			{ eng: "20", kor: "스물" },
			{ eng: "30", kor: "서른" },
			{ eng: "40", kor: "마흔" },
			{ eng: "50", kor: "쉰" },
			{ eng: "60", kor: "예순" },
			{ eng: "70", kor: "이른" },
			{ eng: "80", kor: "여든" },
			{ eng: "90", kor: "아흔" },
			{ eng: "100", kor: "백" }
		]
	},
	{
		category: "Numbers (Sino-Korean)",
		entries: [
			{ eng: "0", kor: "공" },
			{ eng: "1", kor: "일" },
			{ eng: "2", kor: "이" },
			{ eng: "3", kor: "삼" },
			{ eng: "4", kor: "사" },
			{ eng: "5", kor: "오" },
			{ eng: "6", kor: "육" },
			{ eng: "7", kor: "칠" },
			{ eng: "8", kor: "팔" },
			{ eng: "9", kor: "구" },
			{ eng: "10", kor: "십" },
			{ eng: "100", kor: "백" },
			{ eng: "1,000", kor: "천" },
			{ eng: "10,000", kor: "만" },
			{ eng: "100,000", kor: "십만" },
			{ eng: "1,000,000", kor: "백만" },
			{ eng: "10,000,000", kor: "천만" },
			{ eng: "100,000,000", kor: "억" }
		]
	},
	{
		category: "Parts of the Body",
		entries: [
			{ eng: "Body", kor: "몸/신체" },
			{ eng: "Head", kor: "머리" },
			{ eng: "Face", kor: "얼굴" },
			{ eng: "Eye", kor: "눈" },
			{ eng: "Nose", kor: "코" },
			{ eng: "Mouth", kor: "입" },
			{ eng: "Tooth", kor: "이" },
			{ eng: "Ear", kor: "귀" },
			{ eng: "Neck/Throat", kor: "목" },
			{ eng: "Shoulder", kor: "어깨" },
			{ eng: "Arm", kor: "팔" },
			{ eng: "Belly/Stomach", kor: "배" },
			{ eng: "Back", kor: "등" },
			{ eng: "Waist", kor: "허리" },
			{ eng: "Hip", kor: "엉덩이" },
			{ eng: "Leg", kor: "다리" },
			{ eng: "Hand", kor: "손" },
			{ eng: "Feet", kor: "발" },
			{ eng: "Hair", kor: "머리카락" },
			{ eng: "Forehead", kor: "이마" },
			{ eng: "Lips", kor: "입술" },
			{ eng: "Elbow", kor: "팔꿈치" },
			{ eng: "Chest", kor: "가슴" },
			{ eng: "Thigh", kor: "허벅지" },
			{ eng: "Knee", kor: "무릎" },
			{ eng: "Calf", kor: "송아지" },
			{ eng: "Wrist", kor: "손목" },
			{ eng: "Finger", kor: "손가락" },
			{ eng: "Ankle", kor: "발목" },
			{ eng: "Toe", kor: "발가락" }
		]
	},
	{
		category: "Fruits",
		entries: [
			{ eng: "Apple", kor: "사과" },
			{ eng: "Pear", kor: "배" },
			{ eng: "Banana", kor: "바나나" },
			{ eng: "Melon", kor: "참외" },
			{ eng: "Pineapple", kor: "파인애플" },
			{ eng: "Strawberry", kor: "딸기" },
			{ eng: "Mandarin Orange", kor: "만다린 오렌지/귤" },
			{ eng: "Grapes", kor: "포도" }
		]
	},
	{
		category: "Places",
		entries: [
			{ eng: "Places", kor: "장소" },
			{ eng: "House", kor: "집" },
			{ eng: "School", kor: "학교" },
			{ eng: "Institute", kor: "학원" },
			{ eng: "Classroom", kor: "교실" },
			{ eng: "Library", kor: "도서관" },
			{ eng: "Embassy", kor: "대사관" },
			{ eng: "Company", kor: "회사" },
			{ eng: "Office", kor: "사무실" },
			{ eng: "Factory", kor: "공장" },
			{ eng: "Bank", kor: "은행" },
			{ eng: "Post Office", kor: "우체국" },
			{ eng: "Police Station", kor: "경찰서" },
			{ eng: "Hospital", kor: "병원" },
			{ eng: "Drugstore", kor: "약국" },
			{ eng: "Bakery", kor: "빵집/빵가게" },
			{ eng: "Supermarket", kor: "슈퍼마켓" },
			{ eng: "Market", kor: "시장" },
			{ eng: "Store", kor: "가게" },
			{ eng: "Convenience Store", kor: "편의점" },
			{ eng: "Department Store", kor: "백화점" },
			{ eng: "Bookstore", kor: "서점" },
			{ eng: "Downtown", kor: "시내" },
			{ eng: "Hometown", kor: "고향" },
			{ eng: "Theater", kor: "극장" },
			{ eng: "Movie Theater/Cinema", kor: "영화관" },
			{ eng: "Restaurant", kor: "식당" },
			{ eng: "Coffee Shop", kor: "커피 숍" },
			{ eng: "Bus Stop", kor: "버스 정류장" },
			{ eng: "Train Station", kor: "기차역" },
			{ eng: "Subway Station", kor: "지하철역" },
			{ eng: "Airport", kor: "공항" },
			{ eng: "Travel Agency", kor: "여행사" },
			{ eng: "Park", kor: "공원" },
			{ eng: "Toilet", kor: "화장실" },
			{ eng: "City Hall", kor: "시청사" },
			{ eng: "Clinic", kor: "진료소" },
			{ eng: "Dormitory", kor: "기숙사" },
			{ eng: "Temple", kor: "신전" },
			{ eng: "Church", kor: "교회" },
			{ eng: "Gymnasium", kor: "경기장" },
			{ eng: "Residence", kor: "댁" },
			{ eng: "Workplace", kor: "공사장" }
		]
	},
	{
		category: "Clothes",
		entries: [
			{ eng: "Pants", kor: "바지" },
			{ eng: "Skirt", kor: "스커트/치마" },
			{ eng: "T-shirt", kor: "티셔츠" },
			{ eng: "Sweater", kor: "스웨터" },
			{ eng: "Coat", kor: "코트" },
			{ eng: "Man's suit", kor: "양복" },
			{ eng: "Necktie", kor: "넥타이" },
			{ eng: "Korean Traditional Costume", kor: "한복" },
			{ eng: "Socks", kor: "양말" },
			{ eng: "Shoes", kor: "신발" },
			{ eng: "Dress Shoes", kor: "구두" },
			{ eng: "Sneakers/Rubber Shoes", kor: "운동화" },
			{ eng: "Eyeglasses", kor: "안경" },
			{ eng: "Umbrella", kor: "우산" },
			{ eng: "Hat", kor: "모자" },
			{ eng: "Gloves", kor: "장갑" },
			{ eng: "Ring", kor: "반지" },
			{ eng: "Earring", kor: "귀걸이" },
			{ eng: "Necklace", kor: "목걸이" },
			{ eng: "Underwear", kor: "속옷" },
			{ eng: "Short Pants", kor: "반바지" }
		]
	},
	{
		category: "People",
		entries: [
			{ eng: "Baby", kor: "아기" },
			{ eng: "Child", kor: "아이/어린이" },
			{ eng: "Woman", kor: "여자" },
			{ eng: "Man", kor: "남자" },
			{ eng: "Teenager", kor: "청소년" },
			{ eng: "Adult", kor: "어른" },
			{ eng: "Miss/Young Lady", kor: "아가씨" },
			{ eng: "Married Woman/Aunt", kor: "아줌마/아주머니" },
			{ eng: "Married Man/Uncle", kor: "아저씨" },
			{ eng: "Teacher(Mr./Ms.)", kor: "선생님" },
			{ eng: "President", kor: "사장(님)" },
			{ eng: "General Manager", kor: "부장(님)" },
			{ eng: "Section Chief", kor: "과장(님)" },
			{ eng: "Factory Manager", kor: "공장장님" },
			{ eng: "Guest/Costumer", kor: "손님" },
			{ eng: "Owner/Host/Hostess", kor: "주인" },
			{ eng: "all of you", kor: "여러분" }
		]
	},
	{
		category: "Name of Country",
		entries: [
			{ eng: "Korea", kor: "한국/대한민국" },
			{ eng: "Philippines", kor: "필리핀" },
			{ eng: "USA", kor: "미국" },
			{ eng: "Japan", kor: "일본" },
			{ eng: "Taiwan", kor: "대만" },
			{ eng: "Vietnam", kor: "베트남" },
			{ eng: "Indonesia", kor: "인도네시아" },
			{ eng: "Sri Lanka", kor: "스리랑카" },
			{ eng: "Thailand", kor: "태국" },
			{ eng: "China", kor: "중국" },
			{ eng: "Germany", kor: "독일" },
			{ eng: "France", kor: "프랑스" },
			{ eng: "Australia", kor: "호주" },
			{ eng: "Canada", kor: "캐나다" }
		]
	},
	{
		category: "Family",
		entries: [
			{ eng: "Grandfather", kor: "할아버지" },
			{ eng: "Grandmother", kor: "할머니" },
			{ eng: "Parents", kor: "부모(님)" },
			{ eng: "Father", kor: "아버지" },
			{ eng: "Mother", kor: "어머니" },
			{ eng: "Married Couple", kor: "부부" },
			{ eng: "Wife", kor: "아내" },
			{ eng: "Husband", kor: "남편" },
			{ eng: "Son", kor: "아들" },
			{ eng: "Daughter", kor: "딸" },
			{ eng: "Younger Sibling", kor: "동생" },
			{ eng: "Younger Sister", kor: "여동생" },
			{ eng: "Younger Brother", kor: "남동생" },
			{ eng: "Man's Elder Brother", kor: "형" },
			{ eng: "Woman's Elder Brother", kor: "오빠" },
			{ eng: "Man's Elder Sister", kor: "누나" },
			{ eng: "Woman's Elder Sister", kor: "언니" },
			{ eng: "Grandson", kor: "손자" },
			{ eng: "Granddaughter", kor: "손녀" },
		]
	},
	{
		category: "Interogative Pronoun",
		entries: [
			{ eng: "How", kor: "어떻게" },
			{ eng: "How many", kor: "몇" },
			{ eng: "How much", kor: "얼마" },
			{ eng: "How long", kor: "얼마나" },
			{ eng: "When", kor: "언제" },
			{ eng: "Where", kor: "어디" },
			{ eng: "Why", kor: "왜" },
			{ eng: "Which", kor: "어느" },
			{ eng: "What kind", kor: "무슨" },
			{ eng: "Who", kor: "누구" },
			{ eng: "Whom", kor: "누구를" },
			{ eng: "Whose", kor: "누구의" },
			{ eng: "What", kor: "무엇/뭐" }
		]
	},
	{
		category: "Transportation",
		entries: [
			{ eng: "Bus", kor: "버스" },
			{ eng: "Taxi", kor: "택시" },
			{ eng: "Motorcycle", kor: "오토바이" },
			{ eng: "Ship", kor: "배" },
			{ eng: "Airplane", kor: "비행기" },
			{ eng: "Bicycle", kor: "자전거" },
			{ eng: "Car", kor: "차/자동차" },
			{ eng: "Train", kor: "기차" },
			{ eng: "Subway", kor: "지하철/열차" }
		]
	},
	{
		category: "Personal Information",
		entries: [
			{ eng: "Name", kor: "이름/성함" },
			{ eng: "Birthday", kor: "생일" },
			{ eng: "Picture", kor: "사진" },
			{ eng: "Address", kor: "주소" },
			{ eng: "Nationality", kor: "국적" },
			{ eng: "Academic Attainment", kor: "학력" },
			{ eng: "Job", kor: "직업" },
			{ eng: "Passport Number", kor: "여권 번호" },
			{ eng: "Mobile Phone Number", kor: "휴대폰 번호" },
			{ eng: "Phone Number", kor: "전화 번호" },
			{ eng: "Gender", kor: "성별" },
			{ eng: "Male", kor: "남성" },
			{ eng: "Female", kor: "여성" },
			{ eng: "Age", kor: "나이" },
			{ eng: "Married", kor: "기혼(기헌)" },
			{ eng: "Single", kor: "미혼(미헌)" },
			{ eng: "Signature", kor: "서명(명)" }
		]
	},
	{
		category: "Foods",
		entries: [
			{ eng: "Cooked rice", kor: "밥" },
			{ eng: "Uncooked Rice", kor: "쌀" },
			{ eng: "Rice roll", kor: "김밥" },
			{ eng: "Bibimbap", kor: "비빔밥" },
			{ eng: "Bread", kor: "빵" },
			{ eng: "Cake", kor: "케이크" },
			{ eng: "Meat", kor: "고기" },
			{ eng: "Pork", kor: "돼지 고기" },
			{ eng: "Chicken", kor: "닭고기" },
			{ eng: "Beef", kor: "쇠고기" },
			{ eng: "Beef Barbeque", kor: "불고기" },
			{ eng: "Fish", kor: "생선" },
			{ eng: "Noodles", kor: "라면" },
			{ eng: "Cut Noodles", kor: "칼국수" },
			{ eng: "Iced Noodles", kor: "냉면" },
			{ eng: "Beverages", kor: "음료수" },
			{ eng: "Water", kor: "물" },
			{ eng: "Juice", kor: "주스" },
			{ eng: "Tea", kor: "차" },
			{ eng: "Coffee", kor: "커피" },
			{ eng: "Milk", kor: "우유" },
			{ eng: "Beer", kor: "맥주" },
			{ eng: "Cola", kor: "콜라" },
			{ eng: "Rice Wine", kor: "소주" },
			{ eng: "Meal", kor: "식사" },
			{ eng: "Breakfast", kor: "아침" },
			{ eng: "Lunch", kor: "점심" },
			{ eng: "Dinner", kor: "저녁" },
			{ eng: "Egg", kor: "달걀/계란" },
			{ eng: "Side Dish", kor: "반찬" },
			{ eng: "Stew/Steam", kor: "찌게" }
		]
	},
	{
		category: "Furniture",
		entries: [
			{ eng: "Sofa", kor: "소파" },
			{ eng: "Desk", kor: "책상" },
			{ eng: "Chair", kor: "의자" },
			{ eng: "Dresser", kor: "옷장" },
			{ eng: "Bookcase", kor: "책장" },
			{ eng: "Drawer", kor: "서랍장" },
			{ eng: "Bed", kor: "침대" },
			{ eng: "Table", kor: "탁자" }
		]
	},
	{
		category: "Industrial Terms",
		entries: [
			{ eng: "Safety", kor: "안전" },
			{ eng: "Safety First", kor: "안전 제일" },
			{ eng: "Safety Gloves", kor: "안전 장갑" },
			{ eng: "Safety Helmet", kor: "안전모" },
			{ eng: "Safety Shoes", kor: "안전화" },
			{ eng: "Safety Belt", kor: "안전 벨트" },
			{ eng: "Safety Harness", kor: "안전 하네스/안전 대" },
			{ eng: "Safety Clothes", kor: "안전 복" },
			{ eng: "Wearing", kor: "착용" },
			{ eng: "Working", kor: "작업" },
			{ eng: "Working Clothes", kor: "작업복" },
			{ eng: "Face Shield", kor: "보안면호" },
			{ eng: "Goggles", kor: "보안경" },
			{ eng: "Earplug", kor: "귀마개" },
			{ eng: "Mask", kor: "마스크" },
			{ eng: "Construction", kor: "공사" },
			{ eng: "Machine", kor: "기계" },
			{ eng: "Danger", kor: "위험" },
			{ eng: "Caution", kor: "주의" },
			{ eng: "Carefulness", kor: "조심" },
			{ eng: "Warning", kor: "경고" },
			{ eng: "Prohibition", kor: "금지" },
			{ eng: "High Voltage", kor: "고전압" },
			{ eng: "Electricity", kor: "전기" },
			{ eng: "Fire", kor: "화기/불/화재" },
			{ eng: "Falling", kor: "낙하물" },
			{ eng: "Falling Down", kor: "추락" },
			{ eng: "Sliding/Slippery", kor: "미끄러지다" },
			{ eng: "Smoking", kor: "흡연" },
			{ eng: "No Smoking", kor: "금연" },
			{ eng: "Emergency Exit", kor: "비상구" },
			{ eng: "Out of order", kor: "고장" },
			{ eng: "Not in use", kor: "사용금지" },
			{ eng: "Repair", kor: "수리" },
			{ eng: "Authorized Personel Only", kor: "줄입금지" },
			{ eng: "No Pedestrian Allowed", kor: "부행급지" },
			{ eng: "No Thouroughfare for Vehicle", kor: "차량릉행금지" }
		]
	},
	{
		category: "Location",
		entries: [
			{ eng: "East", kor: "동쪽" },
			{ eng: "West", kor: "서쪽" },
			{ eng: "South", kor: "남쪽" },
			{ eng: "North", kor: "북쪽" },
			{ eng: "Front", kor: "앞" },
			{ eng: "Behind", kor: "뒤" },
			{ eng: "On/Above", kor: "위" },
			{ eng: "Under/Below", kor: "아래/밑" },
			{ eng: "In", kor: "안" },
			{ eng: "Out", kor: "밖" },
			{ eng: "Left", kor: "왼쪽" },
			{ eng: "Right", kor: "오른쪽" },
			{ eng: "Beside/Next to", kor: "옆에" },
			{ eng: "Nearby", kor: "가까운/근처의" },
			{ eng: "Middle", kor: "가운대/사이" },
			{ eng: "Straight Ahead", kor: "똑바로" },
			{ eng: "Across", kor: "건너편" }
		]
	},
	{
		category: "Electrical Appliances",
		entries: [
			{ eng: "Electrical Appliances", kor: "가전 제품" },
			{ eng: "Television", kor: "텔레비전" },
			{ eng: "Refrigerator", kor: "냉장고" },
			{ eng: "Air Conditioner", kor: "에어컨" },
			{ eng: "Electric Fan", kor: "선풍기" },
			{ eng: "Computer", kor: "컴퓨터" },
			{ eng: "Camera", kor: "카메라/사진기" },
			{ eng: "Telephone", kor: "전화" },
			{ eng: "Radio", kor: "라디오" },
			{ eng: "Video", kor: "비디오" },
			{ eng: "Light", kor: "전등" },
			{ eng: "Microwave Oven", kor: "전자렌지" },
			{ eng: "Washing Machine", kor: "세탁기" },
			{ eng: "Vacuum Cleaner", kor: "청소기" },
			{ eng: "Flat Iron", kor: "다리미" }
		]
	},
	{
		category: "Occupation",
		entries: [
			{ eng: "Occupation", kor: "직업" },
			{ eng: "Student", kor: "학생" },
			{ eng: "Teacher", kor: "선생" },
			{ eng: "Professor", kor: "교수" },
			{ eng: "Doctor", kor: "의사" },
			{ eng: "Nurse", kor: "간호사" },
			{ eng: "Soldier", kor: "군인" },
			{ eng: "Beautician", kor: "미용사" },
			{ eng: "Chef/Cook", kor: "요리사" },
			{ eng: "Housewife", kor: "주부" },
			{ eng: "Police Officer", kor: "경찰관" },
			{ eng: "Fire Fighter", kor: "소방관" },
			{ eng: "Employee", kor: "직원" },
			{ eng: "Company Worker", kor: "회사원" },
			{ eng: "Office Worker", kor: "직장인" },
			{ eng: "Farmer", kor: "농부" },
			{ eng: "Fisherman", kor: "어부" },
			{ eng: "Driver", kor: "운전기사" },
			{ eng: "Flight Attendant/Goverment Employee", kor: "승무원" }
		]
	},
	{
		category: "Sports / Exercise",
		entries: [
			{ eng: "Sports", kor: "스포츠" },
			{ eng: "Exercise", kor: "운동" },
			{ eng: "Basketball", kor: "농구" },
			{ eng: "Soccer", kor: "축구" },
			{ eng: "Volleyball", kor: "배구" },
			{ eng: "Baseball", kor: "야구" },
			{ eng: "Table Tennis", kor: "탁구" },
			{ eng: "Taekwondo", kor: "태권도" },
			{ eng: "Golf", kor: "골프" },
			{ eng: "Skate", kor: "스케이트" },
			{ eng: "Ski", kor: "스키" },
			{ eng: "Swimming", kor: "수영" },
			{ eng: "Hobby", kor: "취미" },
			{ eng: "Painting", kor: "그림" },
			{ eng: "Fishing", kor: "낚시" },
			{ eng: "Taking Picture", kor: "사진을 찍" },
			{ eng: "Listening to Music", kor: "듣고음악" },
			{ eng: "Mountain Climbing", kor: "등산" },
		]
	},
	{
		category: "Work Related Terms",
		entries: [
			{ eng: "Payday", kor: "월급 날" },
			{ eng: "Salary", kor: "월급" },
			{ eng: "Bonus", kor: "상여금" },
			{ eng: "Going to work/Start of work", kor: "출근" },
			{ eng: "Leaving one's work/End of work", kor: "퇴근" },
			{ eng: "Break Time", kor: "휴식" },
			{ eng: "Duty", kor: "근무" },
			{ eng: "Overtime Work", kor: "잔업" },
			{ eng: "Night Time Work", kor: "야근" },
			{ eng: "Business Trip", kor: "출장" },
			{ eng: "Conference", kor: "의회" },
			{ eng: "Cancel", kor: "취소" },
			{ eng: "Dining Together", kor: "회식" },
			{ eng: "Position", kor: "직책" },
			{ eng: "Part Time Job", kor: "아르바이트" }
		]
	},
	{
		category: "Adverb I",
		entries: [
			{ eng: "A lot", kor: "많은" },
			{ eng: "A little/Please", kor: "작은/조금" },
			{ eng: "Always", kor: "항상" },
			{ eng: "Sometimes", kor: "자주" },
			{ eng: "Never", kor: "않다" },
			{ eng: "Already", kor: "벌써" },
			{ eng: "Yet", kor: "아직" },
			{ eng: "Quickly", kor: "빨리" },
			{ eng: "Slowly", kor: "천천히" },
			{ eng: "Ussually", kor: "보통/주로" },
			{ eng: "Very", kor: "아주" },
			{ eng: "Too much", kor: "너무" },
			{ eng: "Well", kor: "잘" },
			{ eng: "Really", kor: "정말" },
			{ eng: "Suddenly", kor: "갑자기" }
		]
	},
	{
		category: "Adverb II",
		entries: [
			{ eng: "Again", kor: "다시" },
			{ eng: "After", kor: "후에" },
			{ eng: "Later", kor: "다음에" },
			{ eng: "Before", kor: "전에" },
			{ eng: "And", kor: "그리고" },
			{ eng: "So", kor: "그래서" },
			{ eng: "But", kor: "그러나/하지만" },
			{ eng: "If so/Then", kor: "그렇다면" },
			{ eng: "By the way", kor: "그런데" },
			{ eng: "Continuously", kor: "계속" },
			{ eng: "Newly", kor: "새로" },
			{ eng: "Early", kor: "일찍" }
		]
	},
	{
		category: "Places in Korea",
		entries: [
			{ eng: "Seoul", kor: "서울" },
			{ eng: "Busan", kor: "부산" },
			{ eng: "Daegu", kor: "대구" },
			{ eng: "Incheon", kor: "인천" },
			{ eng: "Gwangju", kor: "광주" },
			{ eng: "Daejeon", kor: "대전" },
			{ eng: "Ulsan", kor: "울산" },
			{ eng: "Jeju Island", kor: "제주도" }
		]
	},
	{
		category: "Words Related to Time",
		entries: [
			{ eng: "Dawn", kor: "새벽" },
			{ eng: "Morning/Breakfast/AM", kor: "아침/오전" },
			{ eng: "Noon", kor: "정오" },
			{ eng: "Around Noon/Lunch", kor: "정오/점심 식사" },
			{ eng: "Daytime", kor: "낮" },
			{ eng: "PM/Afternoon", kor: "오후" },
			{ eng: "Evening/Dinner", kor: "저녁/저녁 식사" },
			{ eng: "Night", kor: "밤" },
			{ eng: "Holiday", kor: "휴일" },
			{ eng: "Vacation", kor: "휴가" },
			{ eng: "Birthday", kor: "생일" },
			{ eng: "Anniversary", kor: "기념일" },
			{ eng: "Yesterday", kor: "어제" },
			{ eng: "Today", kor: "오늘" },
			{ eng: "Tomorrow", kor: "내일" },
			{ eng: "Last week", kor: "지난주" },
			{ eng: "Last month", kor: "지난 달" },
			{ eng: "Last year", kor: "작년" },
			{ eng: "This week", kor: "이 주/이번 주" },
			{ eng: "This month", kor: "이 달/이번 달" },
			{ eng: "This year", kor: "올해" },
			{ eng: "Next week", kor: "다음주" },
			{ eng: "Next month", kor: "다음 달" },
			{ eng: "Next year", kor: "내년" },
			{ eng: "Weekdays", kor: "주중" },
			{ eng: "Weekend", kor: "주말" },
			{ eng: "Everyday", kor: "매일" },
			{ eng: "Every week", kor: "매주" },
			{ eng: "Every month", kor: "매 달" },
			{ eng: "Every year", kor: "매년" },
			{ eng: "The day before yesterday", kor: "그제" },
			{ eng: "The day after tomorrow", kor: "모레" },
			{ eng: "Now", kor: "지금" },
			{ eng: "Nowadays/Recently", kor: "요즘" }
		]
	},
	{
		category: "Weather",
		entries: [
			{ eng: "Weather", kor: "날씨" },
			{ eng: "Sun", kor: "태양/해" },
			{ eng: "Moon", kor: "달" },
			{ eng: "Cloud", kor: "구름" },
			{ eng: "Rain", kor: "비" },
			{ eng: "Wind", kor: "바람" },
			{ eng: "Snow", kor: "눈" },
			{ eng: "Wave", kor: "파도" },
			{ eng: "Winter", kor: "겨울" },
			{ eng: "Spring", kor: "봄" },
			{ eng: "Summer", kor: "여름" },
			{ eng: "Fall", kor: "가을" },
			{ eng: "To be cloudy", kor: "흐리다" },
			{ eng: "To be fine", kor: "맑다/촣다" },
			{ eng: "To be warm", kor: "따뜻하다" },
			{ eng: "To be hot", kor: "덥다" },
			{ eng: "To be cool", kor: "시원하다" },
			{ eng: "To be cold", kor: "춥다" }
		]
	}
]